name = "komohaven"
pages_build_output_dir = "."
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "PAYMENTS_KV"
id = "61499baaa55942a0a38458dc0cd3de84"

[[kv_namespaces]]
binding = "AVAIL_KV"
id = "41508b8af57d4e58869ed023c03f6348"